version: "3.8"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      target: migration
    environment:
      # Ensure this connection string includes the correct DB name.
      POSTGRES_URL: postgres://user:password@db:5432/mydb
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_started
    # This service runs the migrations and then exits.
    restart: "no"

  app:
    build:
      context: .
      target: production
    environment:
      POSTGRES_URL: postgres://user:password@db:5432/mydb
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
    command: ["pnpm", "start"]

volumes:
  pgdata:
